image: node:8.9.4

pipelines:
  default:
    - step:
        name: test
        caches:
          - node
        script:
          - ./bitbucket-test.sh
          - echo "Test step finished"

  branches:
    master:
      - step:
          name: Deploy to staging
          deployment: staging
          script:
            - ./bitbucket-test.sh
            - ssh $STAGING_USER@$STAGING_HOST WWW_DIR=$WWW_DIR 'bash -s' < do-deploy.sh
            - echo "Deploy step finished"

      - step:
          name: Deploy to production
          deployment: production
          trigger: manual
          script:
            - ssh $PROD_USER@$PROD_HOST WWW_DIR=$WWW_DIR 'bash -s' < do-deploy.sh
            - echo "Deploy step finished"
