image: node:8.9.4

pipelines:
  default:
    - step:
        name: test
        caches:
          - node
        script:
          - ./bitbucket-test.sh
          - echo "Test step finished"

  branches:
    master:
      - step:
          name: Deploy to staging
          deployment: staging
          # trigger: manual
          script:
            - ./bitbucket-test.sh
            - ssh $STAGING_USER@$STAGING_HOST 'bash -s' < do-deploy.sh
            - echo "Deploy step finished"
